name: Track Pull Request and Subscriber Version Id
 
on:
  push:
   branches: [ develop ]
  
 
jobs:
  track_changes:
    runs-on: ubuntu-latest
    steps:
        - uses: 8BitJonny/gh-get-current-pr@3.0.0
          id: PR
  
        - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
   
