name: Track Pull Request and Subscriber Version Id
 
on:
  push:
   branches: [ develop ]
  
 
jobs:
  track_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s
 
