name: Generate Code Review Report from GitHub
on:
  workflow_dispatch:
    inputs:
        branch:
            description: 'Branch to run the workflow'
            default: 'develop'
            required: true

jobs:
  generate-report:
    name: Generate Code Review Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Merged Pull Request Information
        uses: coin-tracker/get-merged-pull-request@v1.1
        id: pr_review_comments
        with:
            github_token: ${{ secrets.GH_TOKEN }}
            pull-request-number: ${{ github.event.inputs.number }}
            format: markdown

      - name: Create Markdown Report
        id: create_report
        run: |
          echo "** Code Review Report **" > report.md
          echo "Pull Request #${{ github.event.inputs.pull_request_number }}" >> report.md
          echo "Review Comments:" >> report.md
          echo"${{ steps.pr_review_comments.outputs.body }}" >> report.md

      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0    
        with:
          input_path: report.md
          output_dir: report.pdf
    
      - name: Upload CICD Scratch Org Details
        uses: actions/upload-artifact@v4
        with:
          name: code-review-report
          path: report.pdf
