name: Pull Request Workflow for Unlocked Packages Deployment
on:
  push:
    branches: [ develop, uat ]
    paths:
      - 'cmd-loader/main/default/**'
  pull_request:
    branches: [ develop, uat ]

jobs:
  validate_pull_request:
    name: Validation of Pull Request
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
      TARGET_BRANCH: ${{ github.base_ref }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install SFDX CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Install SGD Plugin
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Dev Int Sandbox-Validation
        if: ${{ github.base_ref == 'develop' }}
        run: |
          echo ${{secrets.AUTHURL_COPADOINT}} > ./AUTHURL_COPADOINT.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOINT.txt -a devint
          mkdir changed-sources
          sfdx sgd:source:delta -a 61.0 --to "HEAD" --from "origin/develop" --output changed-sources/ --generate-delta
          echo -e "--- package.xml generated with added and modified metadata ---"
          cat changed-sources/package/package.xml
          sf project deploy validate --manifest changed-sources/package/package.xml -o devint --test-level RunLocalTests --verbose -w 20

      - name: UAT Sandbox-Validation
        if: ${{ github.base_ref == 'uat' }}
        run: |
          echo ${{secrets.AUTHURL_COPADOUAT}} > ./AUTHURL_COPADOUAT.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOUAT.txt -a uat
          mkdir changed-sources
          sfdx sgd:source:delta -a 61.0 --to "HEAD" --from "origin/uat" --output changed-sources/ --generate-delta
          echo -e "--- package.xml generated with added and modified metadata ---"
          cat changed-sources/package/package.xml
          sf project deploy validate --manifest changed-sources/package/package.xml -o uat --test-level RunLocalTests --verbose -w 20

  code_coverage_report:
    name: Apex Code Coverage Report
    needs: validate_pull_request
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install SFDX CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Authorization to DevHub & Create Scratch Org
        run: |
          echo ${{secrets.AUTHURL_COPADOPROD}} > ./AUTHURL_COPADOPROD.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOPROD.txt -a devhub -d
          sfdx force:org:create -f config/project-scratch-def.json -a ci_scratch -s -d 1

      - name: Apex Code Coverage Report Generation
        run: |
          sfdx force:source:push
          sfdx force:apex:test:run -c -r json -d ./tests/apex -u ci_scratch -w 20

      - name: Upload Apex Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: apex-code-coverage
          path: tests/apex/test-result-codecoverage.json
  
      - name: Delete scratch org
        if: always()
        run: sfdx force:org:delete -p -u ci_scratch
        
  sonar_scan:
    name: SonarQube Scan
    needs: code_coverage_report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Apex Code coverage Report
        uses: actions/download-artifact@v2
        with:
          name: apex-code-coverage
          path: tests/apex

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy_package:
    name: Unlocked Package Installation
    if: always() && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install SFDX CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Authorize DevHub
        run: |
          echo ${{secrets.AUTHURL_COPADOPROD}} > ./AUTHURL_COPADOPROD.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOPROD.txt -a devhub

      - name: Dev Int Sandbox-Package Install
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo ${{secrets.AUTHURL_COPADOPROD}} > ./AUTHURL_COPADOPROD.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOPROD.txt -a devhub
          echo ${{secrets.AUTHURL_COPADOINT}} > ./AUTHURL_COPADOINT.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOINT.txt -a devint
          sfdx force:package:version:create -x -p "PackageTest" -w 60 -v devhub -b develop --code-coverage
          echo "Package Version created successfully"
          new_version_id=$(grep -o "04t[[:alnum:]]\{15\}" sfdx-project.json | tail -n1)
          test $(sfdx force:package:version:report -v devhub -p $new_version_id --json | jq .result.HasPassedCodeCoverageCheck) = 'true'
          sfdx force:package:install -p $new_version_id -o devint --wait 10 --publishwait 10

      - name: UAT Sandbox-Package Install
        if: ${{ github.ref == 'refs/heads/uat' }}
        run: |
          echo ${{secrets.AUTHURL_COPADOUAT}} > ./AUTHURL_COPADOUAT.txt
          sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOUAT.txt -a uat
          sfdx force:package:version:create -x -p "PackageTest" -w 60 -v devhub -b uat --code-coverage
          new_version_id=$(grep -o "04t[[:alnum:]]\{15\}" sfdx-project.json | tail -n1)
          echo "version_id=${new_version_id}" >> $GITHUB_ENV
          test $(sfdx force:package:version:report -v devhub -p "$version_id" --json | jq .result.HasPassedCodeCoverageCheck) = 'true'
          sfdx force:package:install -p "$version_id" -o uat --wait 10 --publishwait 10

      - name: Store new version id
        run: |
          sed -i -e "s/04t[[:alnum:]]\{15\}/${version_id}/" README.md
          git config user.name "release[bot]"
          git config user.email "<>"
          git add README.md
          git add sfdx-project.json
          git commit -m "Updating new pre-release version"
          git push