name: Pull Request to Develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  validate_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node JS
      uses: actions/setup-node@v3
      with:
          node-version: 18

    - name: Install SFDX CLI
      run: |
          npm install @salesforce/cli --global
          echo sf version
          sf --version
    
    - name: Install jq
      run: |
        sudo apt-get install jq
    
    - name: Populate auth file
      shell: bash
      run: 'echo ${{secrets.AUTHURL_COPADOPROD}} > ./AUTHURL_COPADOPROD.txt'
    
    - name: Authenticate Dev Hub
      run: 'sfdx force:auth:sfdxurl:store -f ./AUTHURL_COPADOPROD.txt -a devhub -d'

    - name: Create scratch org
      run: 'sfdx force:org:create -f config/project-scratch-def.json -a ci_scratch -s -d 1'
    
    - name: Push source to scratch org / Code Validation
      shell: bash
      run: |
          sfdx force:source:deploy -c -p cmd-loader/main/default -l RunLocalTests -u ci_scratch --verbose > code-coverage.json
          cat code-coverage.json

    - name: Sonar Cloud scan
      if: always()
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Delete scratch org
      if: always()
      run: 'sfdx force:org:delete -p -u ci_scratch'